# Build and tag using commit sha

steps:

- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/cicd-test:${COMMIT_SHA}', '.']
  #args: ['build', '-t', 'asia-south1-docker.pkg.dev/$PROJECT_ID/cicd-test:${COMMIT_SHA}', '.']
#images:
#  - 'asia-south1-docker.pkg.dev/$PROJECT_ID/cicd-test:${COMMIT_SHA}'
     


# Push the container image


- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/cicd-test:${COMMIT_SHA}']
  #args: ['push', 'asia-south1-docker.pkg.dev/$PROJECT_ID/cicd-test:${COMMIT_SHA}']
#images:
#  - 'gcr.io/$PROJECT_ID/cicd-test:${COMMIT_SHA}'
# Create release in Google Cloud Deploy

- name: gcr.io/google.com/cloudsdktool/cloud-sdk
  entrypoint: gcloud
  args:
    [
      "deploy", "releases", "create", "rel-${SHORT_SHA}",
      "--delivery-pipeline", "gitops",
      "--region", "asia-east1",
      "--annotations", "commitId=${REVISION_ID}",
      "--images", "aman-clouddeploy-image=gcr.io/$PROJECT_ID/cicd-test:${COMMIT_SHA}"
    ]

