#Delivery Pipeline for our clusters

apiVersion: deploy.cloud.google.com/v1
kind: DeliveryPipeline
metadata:
 name: gitops
description: main application pipeline
serialPipeline:
  stages:
  - targetId: qsdev
#   - targetId: qsprod
---

#Our 1st Cluster TARGET
apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
 name: qsdev
description: development cluster
gke:
 cluster:  projects/$PROJECT_ID/locations/asia-south1/clusters/prod-cluster
 
---

# #Our 2st Cluster TARGET
# apiVersion: deploy.cloud.google.com/v1
# kind: Target
# metadata:
#  name: qsprod
# description: production cluster
# gke:
#  cluster:  projects/$PROJECT_ID/locations/asia-south1-a/clusters/prod-cluster

