apiVersion: apps/v1
kind: Deployment
metadata:
  name: clouddeploy-deployment-nginx
  labels:
    app: myapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp
        image: aman-demo-image
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: clouddeploy-service-nginx
spec:
  selector:
    app: myapp
  ports:
    - port: 80
      targetPort: 80
  type: LoadBalancer
